# This workflow will build and push a node.js application to an Azure Web App when a release is created.
#
# To configure this workflow:
#
# 1. Set up a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE with the value of your Azure publish profile.
#
# 2. Change the values for the AZURE_WEBAPP_NAME, AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables  (below).
#
# For more information on GitHub Actions for Azure, refer to https://github.com/Azure/Actions
# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
on:
  push:
    branches:
      - master

env:
  NODE_VERSION: "10.x" # set this to the node version to use
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: "eu-central-1"
  AWS_S3_BUCKET: "sites-frontend"

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install, build, and test
        run: |
          npm install
          npm run build

      #main site
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete --cache-control max-age=300
        env:
          SOURCE_DIR: "public/appBin"
          DEST_DIR: "old-rollingscopes-com"

      # city sites
      # - uses: jakejarvis/s3-sync-action@master
      #   with:
      #     args: --acl public-read --follow-symlinks --delete --cache-control max-age=300
      #   env:
      #     AWS_S3_BUCKET: sites-frontend
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: "eu-central-1"
      #     SOURCE_DIR: "public/appBin"
      #     DEST_DIR: "brest-rollingscopes-com"
      # - uses: jakejarvis/s3-sync-action@master
      #   with:
      #     args: --acl public-read --follow-symlinks --delete --cache-control max-age=300
      #   env:
      #     AWS_S3_BUCKET: sites-frontend
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: "eu-central-1"
      #     SOURCE_DIR: "public/appBin"
      #     DEST_DIR: "gomel-rollingscopes-com"
      # - uses: jakejarvis/s3-sync-action@master
      #   with:
      #     args: --acl public-read --follow-symlinks --delete --cache-control max-age=300
      #   env:
      #     AWS_S3_BUCKET: sites-frontend
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: "eu-central-1"
      #     SOURCE_DIR: "public/appBin"
      #     DEST_DIR: "grodno-rollingscopes-com"
      # - uses: jakejarvis/s3-sync-action@master
      #   with:
      #     args: --acl public-read --follow-symlinks --delete --cache-control max-age=300
      #   env:
      #     AWS_S3_BUCKET: "mogilev.rollingscopes.com"
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: "eu-central-1"
      #     SOURCE_DIR: "public/appBin"
      # - uses: jakejarvis/s3-sync-action@master
      #   with:
      #     args: --acl public-read --follow-symlinks --delete --cache-control max-age=300
      #   env:
      #     AWS_S3_BUCKET: "minsk.rollingscopes.com"
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: "eu-central-1"
      #     SOURCE_DIR: "public/appBin"
      # - uses: jakejarvis/s3-sync-action@master
      #   with:
      #     args: --acl public-read --follow-symlinks --delete --cache-control max-age=300
      #   env:
      #     AWS_S3_BUCKET: "krakow.rollingscopes.com"
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: "eu-central-1"
      #     SOURCE_DIR: "public/appBin"
      # - uses: jakejarvis/s3-sync-action@master
      #   with:
      #     args: --acl public-read --follow-symlinks --delete --cache-control max-age=300
      #   env:
      #     AWS_S3_BUCKET: "gdansk.rollingscopes.com"
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: "eu-central-1"
      #     SOURCE_DIR: "public/appBin"
      # - uses: jakejarvis/s3-sync-action@master
      #   with:
      #     args: --acl public-read --follow-symlinks --delete --cache-control max-age=300
      #   env:
      #     AWS_S3_BUCKET: "tashkent.rollingscopes.com"
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: "eu-central-1"
      #     SOURCE_DIR: "public/appBin"
      # - uses: jakejarvis/s3-sync-action@master
      #   with:
      #     args: --acl public-read --follow-symlinks --delete --cache-control max-age=300
      #   env:
      #     AWS_S3_BUCKET: "moscow.rollingscopes.com"
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: "eu-central-1"
      #     SOURCE_DIR: "public/appBin"

      # conf sites
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete --cache-control max-age=300
        env:
          SOURCE_DIR: "public/conferenceBin"
          DEST_DIR: 2018-conf-rollingscopes-com
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete --cache-control max-age=300
        env:
          SOURCE_DIR: "public/conferenceBin/archive/2017"
          DEST_DIR: 2017-conf-rollingscopes-com
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete --cache-control max-age=300
        env:
          SOURCE_DIR: "public/conferenceBin/archive/2016"
          DEST_DIR: 2016-conf-rollingscopes-com
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete --cache-control max-age=300
        env:
          SOURCE_DIR: "public/conferenceBin/archive/2015"
          DEST_DIR: 2015-conf-rollingscopes-com
